sonar.projectKey=flowia-frontend
sonar.projectName=grupo e - flowia frontend

sonar.host.url=https://sedimentologic-crescentlike-tijuana.ngrok-free.dev
sonar.token=sqa_80d211278e16739e8db28391b49ead22c61d0b2e

sonar.sources=.

sonar.exclusions=node_modules/**,.next/**,out/**,public/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json